@startuml
left to right direction
actor "Ciudadano" as ciu
actor "Ciudadano extranjero" as ciuE

usecase "Registrar entrada" as (regis)
usecase "Tomar huellas" as (huellas)

ciu -- regis
ciuE -- huellas
ciuE --> ciu
huellas ..> regis :<<extend>>
@enduml