@startuml

actor "Cliente" as cl

"Confirmar Pedido" as (Confirmar)
"Cancelar Pedido" as (Cancelar)
"Devolver Cambio" as (Devolver)

cl -- Confirmar
cl -- Cancelar
Confirmar ..> Devolver:<<include>>
Cancelar ..> Devolver:<<include>>
@enduml