@startuml
left to right direction
actor "Usuario" as us
actor "Administrador" as admin

usecase "Iniciar sesion" as (login)
usecase "Recuperar contraseña" as (recover)
usecase "Modificar contraseña" as (modify)
usecase "Cerrar sesion" as (logout)

usecase "Registrar usuario" as (Registrar)
usecase "Instalar programa" as (install)

us -- login
us -- recover
us -- modify
us -- logout

admin -- Registrar
admin -- install
admin --> us

@enduml